name: Hello World!

on:
  push:

jobs:
  hello_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Print date
        run: |
          date
      - name: Print contents
        run: |
          ls
