name: Periodic health check

on:
  push:

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check health
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://calm-thicket-66229.herokuapp.com/sgsrg