name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "calm-thicket-66229"
          heroku_email: "joonas.vanhalakka@helsinki.fi"
          healthcheck: "https://calm-thicket-66229.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: Notify success
        echo:
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') && job.status == 'success'}}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: commit,author,took
          custom_payload: |
            {
              attachments: [{
                color: 'good'
                text: `A new version deployed to https://calm-thicket-66229.herokuapp.com/ (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR}. \nBuild took ${process.env.AS_TOOK}.`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Notify failure
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') && job.status != 'success'}}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}