name: Testing stuff

on:
  push:

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: npm run eslint
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: heroku api key
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo "$HEROKU_API_KEY"
   
      #- name: Notify success
      #  if: ${{success()}}
      #  uses: 8398a7/action-slack@v3
      #  with:
      #    status: custom
      #    fields: commit,author,took
      #    custom_payload: |
      #      {
      #        attachments: [{
      #          color: 'good',
      #          text: `(${process.env.AS_COMMIT}) \nBuild took ${process.env.AS_TOOK}.`
      #        }]
      #      }
      #  env:
      #    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #- name: Notify failure
      #  if: ${{always() && failure()}}
      #  uses: 8398a7/action-slack@v3
      #  with:
      #    status: ${{ job.status }}
      #    fields: took
      #  env:
      #    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


      
